### ISSUE TITLE
Requirements Problem 

### ISSUE THREAD

**Issue by cisasam** [INTO-CPS-Association/example_digital-twin_incubator#43]
**Expected Behaviour:**
Everything runs with a fresh virtual environment created with the packages given by `software/requirements.txt`.

**Actual Behaviour:**
An exception is thrown as the startup.start_all_services starts running. The exception is:

`urllib3.exceptions.URLSchemeUnknown.Not supported URL scheme http+docker`

This has been reproduced in three different machines.

**Suspected Cause (credit to @mortenhaahr):**
As `software/requirements.txt` does not specify the version of the packages, the newest version is installed. Either docker or urllib3 has deprecated http in favour of https so the URL scheme http+docker is no longer supported.

**Workaround:**
Get the requirements by freezing them from an older virtual environment that works.

**Comment by mortenhaahr** [comment]
@clagms I can help on this but I need to understand if there is a reason why the dependency versions are left unspecified

**Comment by clagms** [comment]
I wish to understand better what is really causing this issue: we do not depend directly on `urllib`. The hypothesis is that the `docker` package that does so. So one option is to freeze the docker package version. 

However I'm having trouble reproducing this. I have deleted the virtual environment and reinstalled everything from the `requirements.txt` file with no constraints on versioning. 
Then I run `python -m startup.start_all_services` and it works: no exception is thrown.

Can you clarify which python version you're using, and paste here a freeze of your environment? Sorry for the trouble.

My python: `Python 3.11.2`

My `pip freeze`:
```
certifi==2024.2.2
charset-normalizer==3.3.2
contourpy==1.2.1
control==0.10.0
cycler==0.12.1
deprecation==2.1.0
docker==7.1.0
filterpy==1.4.5
fonttools==4.52.1
idna==3.7
influxdb-client==1.43.0
kiwisolver==1.4.5
matplotlib==3.9.0
mpmath==1.3.0
numpy==1.26.4
oomodelling==0.1.0
packaging==24.0
pandas==2.2.2
pika==1.3.2
pillow==10.3.0
plotly==5.22.0
pyhocon==0.3.60
pyparsing==3.1.2
python-dateutil==2.9.0.post0
pytz==2024.1
pywin32==306
reactivex==4.0.4
requests==2.32.2
scipy==1.13.1
six==1.16.0
sympy==1.12
tenacity==8.3.0
typing_extensions==4.12.0
tzdata==2024.1
urllib3==2.2.1
```

**Comment by cisasam** [comment]
Hi Claudio,
This is the freeze:
certifi==2024.2.2
charset-normalizer==3.3.2
contourpy==1.1.1
control==0.9.4
cycler==0.12.1
deprecation==2.1.0
docker==7.0.0
filterpy==1.4.5
fonttools==4.51.0
idna==3.7
importlib-resources==6.4.0
influxdb-client==1.43.0
kiwisolver==1.4.5
matplotlib==3.7.5
mpmath==1.3.0
numpy==1.24.4
oomodelling==0.1.0
packaging==24.0
pandas==2.0.3
pika==1.3.2
pillow==10.3.0
plotly==5.22.0
pyhocon==0.3.60
pyparsing==3.1.2
python-dateutil==2.9.0.post0
pytz==2024.1
reactivex==4.0.4
requests==2.32.1
scipy==1.10.1
six==1.16.0
sympy==1.12
tenacity==8.3.0
typing-extensions==4.11.0
tzdata==2024.1
urllib3==2.2.1
zipp==3.18.2

and this is the whole exception trace:
Traceback (most recent call last):
  File "/home/carlos/Desktop/example_digital-twin_incubator/software/env/lib/python3.8/site-packages/requests/adapters.py", line 532, in send
    conn = self._get_connection(request, verify, proxies=proxies, cert=cert)
  File "/home/carlos/Desktop/example_digital-twin_incubator/software/env/lib/python3.8/site-packages/requests/adapters.py", line 400, in _get_connection
    conn = self.poolmanager.connection_from_host(
  File "/home/carlos/Desktop/example_digital-twin_incubator/software/env/lib/python3.8/site-packages/urllib3/poolmanager.py", line 304, in connection_from_host
    return self.connection_from_context(request_context)
  File "/home/carlos/Desktop/example_digital-twin_incubator/software/env/lib/python3.8/site-packages/urllib3/poolmanager.py", line 326, in connection_from_context
    raise URLSchemeUnknown(scheme)
urllib3.exceptions.URLSchemeUnknown: Not supported URL scheme http+docker

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/carlos/Desktop/example_digital-twin_incubator/software/env/lib/python3.8/site-packages/docker/api/client.py", line 213, in _retrieve_server_version
    return self.version(api_version=False)["ApiVersion"]
  File "/home/carlos/Desktop/example_digital-twin_incubator/software/env/lib/python3.8/site-packages/docker/api/daemon.py", line 181, in version
    return self._result(self._get(url), json=True)
  File "/home/carlos/Desktop/example_digital-twin_incubator/software/env/lib/python3.8/site-packages/docker/utils/decorators.py", line 44, in inner
    return f(self, *args, **kwargs)
  File "/home/carlos/Desktop/example_digital-twin_incubator/software/env/lib/python3.8/site-packages/docker/api/client.py", line 236, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/home/carlos/Desktop/example_digital-twin_incubator/software/env/lib/python3.8/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/home/carlos/Desktop/example_digital-twin_incubator/software/env/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/carlos/Desktop/example_digital-twin_incubator/software/env/lib/python3.8/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/carlos/Desktop/example_digital-twin_incubator/software/env/lib/python3.8/site-packages/requests/adapters.py", line 534, in send
    raise InvalidURL(e, request=request)
requests.exceptions.InvalidURL: Not supported URL scheme http+docker

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/carlos/Desktop/example_digital-twin_incubator/software/startup/start_all_services.py", line 18, in <module>
    start_docker_rabbitmq()
  File "/home/carlos/Desktop/example_digital-twin_incubator/software/startup/start_docker_rabbitmq.py", line 26, in start_docker_rabbitmq
    kill_container(containerName)
  File "/home/carlos/Desktop/example_digital-twin_incubator/software/startup/utils/docker_service_starter.py", line 11, in kill_container
    client = docker.from_env()
  File "/home/carlos/Desktop/example_digital-twin_incubator/software/env/lib/python3.8/site-packages/docker/client.py", line 94, in from_env
    return cls(
  File "/home/carlos/Desktop/example_digital-twin_incubator/software/env/lib/python3.8/site-packages/docker/client.py", line 45, in __init__
    self.api = APIClient(*args, **kwargs)
  File "/home/carlos/Desktop/example_digital-twin_incubator/software/env/lib/python3.8/site-packages/docker/api/client.py", line 197, in __init__
    self._version = self._retrieve_server_version()
  File "/home/carlos/Desktop/example_digital-twin_incubator/software/env/lib/python3.8/site-packages/docker/api/client.py", line 220, in _retrieve_server_version
    raise DockerException(
docker.errors.DockerException: Error while fetching server API version: Not supported URL scheme http+docker


Kind regards,


Carlos Isasa

PhD. Student

Software Engineering and Computing Systems

email: ***@***.***

Aarhus University

Department of Electrical and Computer Engineering

Finlandsgade 22 (visiting Helsingforsgade 10)

8200  Aarhus N

Denmark

Building 5123, room 326


________________________________
De: Cláudio Gomes ***@***.***>
Enviado: lunes, 27 de mayo de 2024 8:04
Para: INTO-CPS-Association/example_digital-twin_incubator ***@***.***>
Cc: Carlos Ignacio Isasa Martin ***@***.***>; Author ***@***.***>
Asunto: Re: [INTO-CPS-Association/example_digital-twin_incubator] Requirements Problem (Issue #43)


I wish to understand better what is really causing this issue: we do not depend directly on urllib. The hypothesis is that the docker package that does so. So one option is to freeze the docker package version.

However I'm having trouble reproducing this. I have deleted the virtual environment and reinstalled everything from the requirements.txt file with no constraints on versioning.
Then I run python -m startup.start_all_services and it works: no exception is thrown.

Can you clarify which python version you're using, and paste here a freeze of your environment? Sorry for the trouble.

My python: Python 3.11.2

My pip freeze:

certifi==2024.2.2
charset-normalizer==3.3.2
contourpy==1.2.1
control==0.10.0
cycler==0.12.1
deprecation==2.1.0
docker==7.1.0
filterpy==1.4.5
fonttools==4.52.1
idna==3.7
influxdb-client==1.43.0
kiwisolver==1.4.5
matplotlib==3.9.0
mpmath==1.3.0
numpy==1.26.4
oomodelling==0.1.0
packaging==24.0
pandas==2.2.2
pika==1.3.2
pillow==10.3.0
plotly==5.22.0
pyhocon==0.3.60
pyparsing==3.1.2
python-dateutil==2.9.0.post0
pytz==2024.1
pywin32==306
reactivex==4.0.4
requests==2.32.2
scipy==1.13.1
six==1.16.0
sympy==1.12
tenacity==8.3.0
typing_extensions==4.12.0
tzdata==2024.1
urllib3==2.2.1

**Comment by clagms** [comment]
From a call with @mortenhaahr , and the reply by @cisasam , it seems that both of you are running older versions of python (Carlos with 3.8 and Morten with 3.10), and both have an older version of the docker package (7.0.0 vs 7.1.0).

I have now confirmed that the problem is the docker package being at version 7.0.0. 

I will fix that dependency but recommend that you both upgrade your environments. I haven't tested this incubator stuff on python 3.8.

**Comment by cisasam** [comment]
Hi Claudio,
I can also tell you that with Python 3.12.3 on my MacOS (previous specs were from the Ubuntu machine as I didnt want to re install everything) it gives the same exception.

Kind regards,


Carlos Isasa

PhD. Student

Software Engineering and Computing Systems

email: ***@***.***

Aarhus University

Department of Electrical and Computer Engineering

Finlandsgade 22 (visiting Helsingforsgade 10)

8200  Aarhus N

Denmark

Building 5123, room 326


________________________________
De: Cláudio Gomes ***@***.***>
Enviado: lunes, 27 de mayo de 2024 8:20
Para: INTO-CPS-Association/example_digital-twin_incubator ***@***.***>
Cc: Carlos Ignacio Isasa Martin ***@***.***>; Mention ***@***.***>
Asunto: Re: [INTO-CPS-Association/example_digital-twin_incubator] Requirements Problem (Issue #43)


From a call with @mortenhaahr<https://github.com/mortenhaahr> , and the reply by @cisasam<https://github.com/cisasam> , it seems that both of you are running older versions of python (Carlos with 3.8 and Morten with 3.10), and both have an older version of the docker package (7.0.0 vs 7.1.0).

I have now confirmed that the problem is the docker package being at version 7.0.0.

I will fix that dependency but recommend that you both upgrade your environments. I haven't tested this incubator stuff on python 3.8.
